PyTorch stands out as a leading library for numerical computation, particularly in the realm of machine learning research. Similar to NumPy, PyTorch revolves around the concept of Tensors, which are versatile multidimensional arrays. However, what sets PyTorch apart is its seamless integration with CPUs, GPUs, and TPUs, offering flexibility in hardware utilization without necessitating significant alterations to code. Additionally, PyTorch facilitates effortless distribution of computations across multiple devices or machines.

A standout feature of PyTorch is its automatic differentiation capability, enabling the efficient computation of function gradients. This functionality proves indispensable for training machine learning models via gradient descent methods. By harnessing PyTorch's automatic differentiation, practitioners can efficiently compute gradients analytically, streamlining the model optimization process.

To delve into PyTorch effectively, it's crucial to grasp the fundamentals of Tensors. These structures not only resemble NumPy arrays but also boast additional functionalities, making them instrumental in various computational tasks. Thus, understanding Tensors serves as the cornerstone for leveraging PyTorch's capabilities effectively and embarking on successful machine learning endeavors.

A tensor can store a scalar value:



In [1]:
import torch
a = torch.tensor(3)
print(a)

tensor(3)


or an array:



In [2]:
b = torch.tensor([1, 2])
print(b) 

tensor([1, 2])


a matrix:

In [3]:
c = torch.zeros([2, 2])
print(c) 

tensor([[0., 0.],
        [0., 0.]])


or any arbitrary dimensional tensor:



In [4]:
d = torch.rand([2, 2, 2])

Tensors serve as efficient tools for conducting algebraic operations, pivotal in numerous machine learning applications. Among these operations, matrix multiplication stands out as a cornerstone. For instance, suppose there's a need to multiply two random matrices, one of size 3x5 and the other 5x4. This operation can be seamlessly executed using the matrix multiplication (@) operation in PyTorch:

In [5]:
import torch

x = torch.randn([3, 5])
y = torch.randn([5, 4])
z = x @ y

print(z)

tensor([[ 0.1288, -0.2270, -1.7016, -0.2825],
        [-1.0185, -0.6407, -0.0217,  1.3082],
        [-0.6981, -0.3761,  0.0116,  0.2064]])


Similarly, to add two vectors, you can do:



In [9]:
z = x + x

To convert a tensor into a numpy array you can call Tensor's numpy() method:



In [10]:
print(z.numpy())

[[-0.52415884 -2.1994226  -1.9487829  -2.1244855   2.2021441 ]
 [ 1.2353979   0.4547561   1.4146829  -1.7605408  -1.8474518 ]
 [ 0.9261078   0.12827146  1.34049    -0.12805016 -0.44604003]]


And you can always convert a numpy array into a tensor by:


In [12]:
import numpy as np
x = torch.tensor(np.random.normal([3, 5]))